plt.scatter(X_train, y_train, color="blue", label="Train data")
# plt.scatter(X_test, y_test, color="green", label="Test data")
# plt.xlabel("Hours")
# plt.ylabel("Scores")
# plt.legend()
# plt.show()